spring:
  application:
    name: taja

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

api:
  key: ${API_KEY}
  base-url: ${API_BASE_URL}
  status:
    path: ${STATUS_API_PATH}
  station:
    path: ${STATION_API_PATH}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token: 1800000   # 30분
    refresh-token: 604800000 # 7일
