spring:
  application:
    name: taja

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 5s
      connect-timeout: 5s

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000

api:
  bike:
    key: ${BIKE_API_KEY}
    base-url: ${BIKE_API_BASE_URL}
    status:
      path: ${BIKE_STATUS_API_PATH}
    station:
      path: ${BIKE_STATION_API_PATH}
  weather:
    key: ${WEATHER_API_KEY}
    base-url: ${WEATHER_API_BASE_URL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token: 1800000   # 30분
    refresh-token: 604800000 # 7일

cache:
  station:
    ttl-sec: 3600
    refresh-threshold-sec: 10

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        ignoreExceptions:
          - com.taja.global.exception.NoRetryApiException
    instances:
      stationApi:
        baseConfig: default
      weatherApi:
        baseConfig: default
